global:
  scrape_interval: 5s
  external_labels:
    monitor: "codelab-monitor"
scrape_configs:
  - job_name: "review-bot"
    scrape_interval: 5s
    metrics_path: "actuator/prometheus"
    static_configs:
      - targets: ['review-bot-app:8080']
